Testing results verification and error detection.
Used the inutitive, possibly defficent, method to verify the testing results.
Added error detection when some compressing tools are not installed in the
running system.
Added message for ommitting .rar testing.

diff --git a/test/run-test b/test/run-test
--- a/test/run-test
+++ b/test/run-test
@@ -48,10 +48,15 @@ then
 fi
 
 echo "creating .7z compressed files down at $tmp_dir"
-7z a "$tmp_dir/$sample_name.7z" $data_dir > /dev/null
+if [ -e "/usr/bin/7z" ]
+then
+  7z a "$tmp_dir/$sample_name.7z" $data_dir > /dev/null
+else
+  echo ".7z testing is omitted for /usr/bin/7z doesn't exist!"
+fi
 
 echo "creating .zip compressed files down at $tmp_dir"
-zip "$tmp_dir/$sample_name.zip" $data_dir > /dev/null
+zip "$tmp_dir/$sample_name.zip" $data_dir/* > /dev/null
 
 echo "creating .tar compressed files down at $tmp_dir"
 tar -cf "$tmp_dir/$sample_name.tar" $data_dir > /dev/null
@@ -66,14 +71,44 @@ echo "creating .tgz compressed files down at $tmp_dir"
 tar -czf "$tmp_dir/$sample_name.tgz" $data_dir > /dev/null
 
 echo "creating .jar, .war and .ear compressed files down at $tmp_dir"
-jar -cf "$tmp_dir/$sample_name.jar" $data_dir > /dev/null
-jar -cf "$tmp_dir/$sample_name.war" $data_dir > /dev/null
-jar -cf "$tmp_dir/$sample_name.ear" $data_dir > /dev/null
+if [ -e $JAVA_HOME/bin/jar ]
+then
+  jar -cf "$tmp_dir/$sample_name.jar" $data_dir > /dev/null
+  jar -cf "$tmp_dir/$sample_name.war" $data_dir > /dev/null
+  jar -cf "$tmp_dir/$sample_name.ear" $data_dir > /dev/null
+else
+  echo "jar not found according to $JAVA_HOME/bin/jar, use zip instead for .jar, .war, .ear testing."
+  zip -cf "$tmp_dir/$sample_name.jar" $data_dir > /dev/null
+  zip -cf "$tmp_dir/$sample_name.war" $data_dir > /dev/null
+  zip -cf "$tmp_dir/$sample_name.ear" $data_dir > /dev/null
+fi
 
 ## run lily against compressed files
+let failed=0
 for file in $tmp_dir/*
 do
-  lily $file
+  echo "running lily $file"
+  results="`lily $file`"
+  for i in 0 1 2 3 4 5 6 7 8 9
+  do
+    if echo "$results" | grep "$sample_name$i" >& /dev/null
+    then
+      #echo "contents of $file contains $sample_name$i."
+      echo -n
+    else
+      let failed=1
+      echo "contents of $file doesn't contain $sample_name$i!"
+      break
+    fi
+  done
 done
+if [ $failed -ne 0 ]
+then
+  echo "testing failed!"
+  exit 1
+else
+  echo ".rar testing is omitted for no trivial way to create a .rar file."
+  echo "testing completed successfully!"
+fi
 
 # TODO: from data sample file create a list of files from which generate compressed files of all supported file formats
